services:
  - type: web
    name: dxf-visual-ilot-pro
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000

databases:
  - name: dxf-visual-ilot-pro-db
    databaseName: dxf_visual_ilot
    user: dxf_user